workflows:
  build_apk:
    name: Build APK
    max_build_duration: 30
    environment:
      sdk: "flutter"
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
